version: '3'
services:
  spark:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark-jupyter
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./src:/home/jovyan
    environment:
      GRANT_SUDO: 'yes'
      ENABLE_HTTPS: 'false'
    user: "root"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  producer:
    container_name: producer
    image: miciav/producer:latest
    environment:
       kafkauri: kafka:9092
       topic: my_topic
    depends_on:
      - kafka
      - zookeeper
    links:
      - kafka
    restart: on-failure:10
